### ISSUE TITLE
Feature: macos compatibility

### ISSUE THREAD

**Issue by switchdo** [MrClock8163/Arma3ObjectBuilder#39] opened 2024-01-25 11:20 UTC
### Category

Other

### Name of new feature

macos compatibility

### Description

Could this be allowed to be installed in blender for mac? It seems to stop the installation due to trying to read the windows registry. Could that be made optional?

**Comment by MrClock8163** [comment] 2024-01-25 13:26
Actually, never mind
I realized the probable cause
The addon tries to import the`winreg` module for the windows registry access, which is not surprisingly not available on non-windows systems
This is only used by the operator to automatically locate the Arma 3 Tools installation
I moved the import inside the function, so it shouldn't error out the whole addon anymore

**Comment by switchdo** [comment] 2024-01-25 19:22
yes but even commenting out import winreg gives the following error message:

<img width="657" alt="Screenshot 2024-01-25 at 19 21 47" src="https://github.com/MrClock8163/Arma3ObjectBuilder/assets/157700732/6dd83f09-7178-429b-b0fd-64dc5e26bbdd">

**Comment by MrClock8163** [comment] 2024-01-25 20:49
That type of error usually arises when you try to update a plugin without closing blender in the process.
Could I ask you to try the following?
1. Remove addon
2. Close Blender
3. Install the addon, but don't active it
4. Close Blender
5. Comment out the `winreg` import in the installed files
6. Start Blender, and try to activate the addon

**Comment by switchdo** [comment] 2024-01-25 21:28
Ok did that twice, it returns the same exact error message

**Comment by switchdo** [comment] 2024-01-25 21:32
And though it shows Object Builder inactive, i see some of the tools available in blender. There is no preferences pane and possibly other features may not be available

**Comment by MrClock8163** [comment] 2024-01-25 22:54
Oh god
I love platform incompatibilities
I'll try to iron out these path inconsistencies for the next release

As for your issue with the error you previously posted, I'm not sure what the issue might be
I can't reproduce it on my machine, and I don't have a Mac to test on

**Comment by MrClock8163** [comment] 2024-01-25 22:56
Which version of Blender ar you running, and which version of the addon?
Also
If you look at the folder containing the installed addon files, are you sure that addon is not in there twice, by accident?

**Comment by switchdo** [comment] 2024-01-26 16:30
It works now!

So besides commenting out the import winreg I had to add the icons path to themes_dir. It was returning FileNotFoundError. I don't know python so have no idea why os.path.dirname would return a different result in windows than on mac.

Then it was returning a NotADirectoryError on the same function but that was due to these stupid .DS_Store files that macos creates all over the place. After deleting those files it activated and now the preferences work and the icons are visible. 

This was Blender 3.6.7 and ObjectBuilder 2.0.0

**Comment by MrClock8163** [comment] 2024-01-26 16:54
Glad to hear it!

The icons folder was erroring out, because I wrote `..\\icons` instead of `../icons`
Windows uses `\` to separate paths by default, but accepts `/` too
Mac and linux on the other hand only accept `/`

Hopefully you won't have to do these manual fixes with the next version, which is coming soon

**Comment by MrClock8163** [comment] 2024-01-26 17:05
Awesome
Thank you for the informations

**Closed** 2024-01-31 19:51 UTC
Labels: feature
